### ISSUE TITLE
Schema parsing errors don't provide any actionable information

### ISSUE THREAD

**Issue by dandv** [Urigo/graphql-modules#1083]
I had a typo in my schema (derived from the basic example) and the error message was useless (just a stack trace never pointing to my code). If the root of the issue isn't GraphQL Modules, can you help me file it with against the relevant package? (I've looked at graphql-js and there didn't seem to be an [issue for unhelpful schema parsing errors](https://github.com/graphql/graphql-js/issues?q=schema+parsing+error+line+number).) On the other hand, if GraphlQL Modules can do something about this, that would be very helpful.

Here's a minimal example:

```ts
import { GraphQLModule } from '@graphql-modules/core';
import gql from 'graphql-tag';

export const UserModule = new GraphQLModule({
  typeDefs: gql`
    type Query {
      hello: String
  `,
  resolvers: {
    Query: {
      hello: (root, args, context) => {
        console.log(context);
      }
    }
  },
});
```

The error was:

```
/home/dandv/prg/gql-modules-context/node_modules/graphql/error/syntaxError.js:24
  return new _GraphQLError.GraphQLError("Syntax Error: ".concat(description), undefined, source, [position]);
         ^
GraphQLError: Syntax Error: Expected Name, found <EOF>
    at syntaxError (/home/dandv/prg/gql-modules-context/node_modules/graphql/error/syntaxError.js:24:10)
    at expectToken (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:1433:32)
    at parseName (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:98:15)
    at parseFieldDefinition (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:870:14)
    at many (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:1524:16)
    at parseFieldsDefinition (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:859:50)
    at parseObjectTypeDefinition (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:813:16)
    at parseTypeSystemDefinition (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:711:16)
    at parseDefinition (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:144:16)
    at many (/home/dandv/prg/gql-modules-context/node_modules/graphql/language/parser.js:1521:16)
```

**Comment by ardatan** [comment]
```
typeDefs: gql`
    type Query {
      hello: String
  `
```
If you use `gql` tag, it will compile string to DocumentNode then send it to GraphQL Modules so there is nothing to do in that case.
For example,
`Foo( Bar ( SomeWrongValue ) )`
In that code, if `Bar` throws an error, `Foo` has nothing to do with it because `Bar` throws the error immediately after the application runs.
