### ISSUE TITLE
context.ɵgetModuleContext is not a function

### ISSUE THREAD

**Issue by sandromartis** [Urigo/graphql-modules#1632]
**Describe the bug**

I'm trying to migrate our codebase from v0 to v1 and I'm running into the following error when using the latest versions of `graphql-modules` and `apollo-server`:
```
{
  "errors": [
    {
      "message": "context.ɵgetModuleContext is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: context.ɵgetModuleContext is not a function",
            "    at wrappedResolver (/Users/Sandro/Development/graphql-modules-testing/dist/graphql-modules/src/module/resolvers.js:92:30)",
            "    at field.resolve (/Users/Sandro/Development/graphql-modules-testing/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveField (/Users/Sandro/Development/graphql-modules-testing/node_modules/graphql/execution/execute.js:464:18)",
            "    at executeFields (/Users/Sandro/Development/graphql-modules-testing/node_modules/graphql/execution/execute.js:292:18)",
            "    at executeOperation (/Users/Sandro/Development/graphql-modules-testing/node_modules/graphql/execution/execute.js:236:122)",
            "    at executeImpl (/Users/Sandro/Development/graphql-modules-testing/node_modules/graphql/execution/execute.js:116:14)",
            "    at Object.execute (/Users/Sandro/Development/graphql-modules-testing/node_modules/graphql/execution/execute.js:60:35)",
            "    at /Users/Sandro/Development/graphql-modules-testing/node_modules/apollo-server-core/src/requestPipeline.ts:549:22",
            "    at Generator.next (<anonymous>)",
            "    at /Users/Sandro/Development/graphql-modules-testing/node_modules/apollo-server-core/dist/requestPipeline.js:8:71"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Am I doing something wrong?

**To Reproduce**
Use this minimal code example:
```ts
import { ApolloServer } from "apollo-server";
import { createApplication, createModule, gql } from "graphql-modules";

const typedef = gql`
  type Query {
    hello: String!
  }
`;

const someModule = createModule({
  id: 'my-module',
  typeDefs: [typedef],
  resolvers: {
    Query: {
      hello: () => 'world',
    },
  },
});

const mainModule = createApplication({
  modules: [someModule],
});

const server = new ApolloServer({
  schema: mainModule.schema
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

**Expected behavior**

I can run the `hello` query without receiving an error.

**Environment:**

package.json:

```
{
  "name": "graphql-modules-testing",
  "version": "1.0.0",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-server": "^2.22.2",
    "graphql": "^15.5.0",
    "graphql-modules": "^1.4.2",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.3"
  }
}

```

**Comment by ardatan** [comment]
You should use `createSchemaForApollo` as described in here;
https://www.graphql-modules.com/docs/get-started#use-your-application

**Comment by sandromartis** [comment]
That worked! Thanks for the fast reply!

`createSchemaForApollo` is marked as experimental in the docs, so I was slightly confused. Thanks for the quick help.

**Comment by cowboyd** [comment]
I'm also seeing this, but not using Apollo server, using `@envelop/core`. What is the difference between `schema` and `schemaForApollo`?

**Comment by b3nab** [comment]
Actually I have the same problem trying to use graphql-modules with @graphql-yoga/node that internally relies on graphql-helix and @envelop 
The code is this:
```
import { createApplication, createModule, gql } from 'graphql-modules'
import { createServer } from '@graphql-yoga/node'

const userModule = createModule({
  id: 'user-module',
  dirname: __dirname,
  typeDefs: [
    gql`
      type Query {
        hello: String!
      }
    `
  ],
  resolvers: {
    Query: {
      hello: () => 'world'
    }
  }
})

const application = createApplication({
  modules: [userModule]
})

const server = createServer({
  schema: application.schema,
})

export const config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
}

export default server.requestListener
```


Are we missing something on the schema creation?

**Comment by ardatan** [comment]
You should use GraphQL Modules plugin from Envelop.
https://www.envelop.dev/plugins/use-graphql-modules

**Comment by cowboyd** [comment]
> You should use GraphQL Modules plugin from Envelop.
> https://www.envelop.dev/plugins/use-graphql-modules

This has made my day 🙌
