### ISSUE TITLE
Accessing `GraphQLModule.schema` from within `resolversComposition` function

### ISSUE THREAD

**Issue by jchapple** [Urigo/graphql-modules#193]
Hello!

I am trying to implement an authentication guard, using resolvers composition, and GraphQL `@directives`. I have observed that `resolversComposition` can be provided as a function that accepts `GraphQLModule`. 

I was hoping to be able to access `GraphQLModule.schema`, in order to access the `GraphQLSchema`, which I'd need to do in order to map logic functions to fields with directives.

However, when I attempt to access `GraphQLModule.schema`, I receive the following error:
```
RangeError: Maximum call stack size exceeded
    at new Injector (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/di/injector.ts:9:21)
    at GraphQLModule.buildSchemaAndInjector (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:395:22)
    at GraphQLModule.get [as schema] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:160:12)
    at exports.resolversComposition (/Users/jackchapple/node-projects/telco-api/src/modules/auth/resolvers-composition.ts:13:56)
    at GraphQLModule.get [as selfResolversComposition] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:319:33)
    at GraphQLModule.buildSchemaAndInjector (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:411:80)
    at GraphQLModule.get [as schema] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:160:12)
    at exports.resolversComposition (/Users/jackchapple/node-projects/telco-api/src/modules/auth/resolvers-composition.ts:13:56)
    at GraphQLModule.get [as selfResolversComposition] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:319:33)
    at GraphQLModule.buildSchemaAndInjector (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:411:80)
    at GraphQLModule.get [as schema] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:160:12)
    at exports.resolversComposition (/Users/jackchapple/node-projects/telco-api/src/modules/auth/resolvers-composition.ts:13:56)
    at GraphQLModule.get [as selfResolversComposition] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:319:33)
    at GraphQLModule.buildSchemaAndInjector (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:411:80)
    at GraphQLModule.get [as schema] (/Users/jackchapple/node-projects/telco-api/node_modules/@graphql-modules/core/src/graphql-module.ts:160:12)
    at exports.resolversComposition (/Users/jackchapple/node-projects/telco-api/src/modules/auth/resolvers-composition.ts:13:56)
printErrorAndExit @ VM98 source-map-support.js:444
process.emit @ VM98 source-map-support.js:457
process._fatalException @ VM10 node.js:628
```

Here's my `resolvers-composition.ts`:
```typescript
import { GraphQLModule } from '@graphql-modules/core';
// import { GraphQLSchema } from 'graphql';
import { authenticated } from './authenticated-guard';
import { validateRole } from './validate-role';

const DIRECTIVE_TO_GUARD = {
  auth: () => authenticated,
  protect: ({ role }) => validateRole(role),
};

export const resolversComposition = (module: GraphQLModule) => {
  console.log('resolversComposition', { schema: module.schema }); // throws
}
```

Am I doing something incorrectly? Many thanks in advance.

**Comment by ardatan** [comment]
You cannot use schema there, because it is not created yet. You can only use config or typeDefs.

**Comment by jchapple** [comment]
I had suspected that might be the case.

I was trying to follow the example written [https://medium.com/the-guild/authentication-and-authorization-in-graphql-and-how-graphql-modules-can-help-fadc1ee5b0c2](here).

In the example at the bottom, something similar is achieved within a `resolversComposition` function by importing `getFieldsWithDirective` from `@graphql-modules/core`, however, I've noticed that isn't exported any more, so that must have been deprecated since the article was written?

What would be the approach for achieving declarative `@directive` mapping with the current API?

**Comment by dotansimha** [comment]
Hi @jchapple ! 
Sorry for the confusion. There was some internal changes in the packages, and we decided to expose `{ typeDefs: DocumentNode }` instead of the schema itself. 
Since 0.2.5, you should be able to get `{ typeDefs }` from the `resolversComposition` function, we also exposed `getFieldsWithDirectives` from `@graphql-modules/utils` package. The API has changes a bit, but I updated the snippet here to reflect the recent changes:
https://gist.github.com/dotansimha/63540221a04b8710c60ac480b5e32422

**Comment by jchapple** [comment]
This is fantastic! Thanks so much for your help. I am really excited about GraphQL modules and seeing where the possibilities take us with SDL-first-development. 🤗
