### ISSUE TITLE
Add support of Object Extensions

### ISSUE THREAD

**Issue by nakhodkiin** [Urigo/graphql-modules#266]
I was playing awhile with `basic-with-dependency-injection` example and suddenly figuerd out that it seems that for now there is some issue with operation on type extension feature of graphQL.

Here is the section from the specification: https://facebook.github.io/graphql/draft/#sec-Object-Extensions wich describes particularly Object type extensions.

I'm defining the `Query` type on `AppModule`
<img width="845" alt="screen shot 2019-01-14 at 4 29 56 pm" src="https://user-images.githubusercontent.com/14351638/51118768-d21ee580-1819-11e9-8231-549b05686dd0.png">

In the `typeDefs` section of the `User` module I want to extend the `Query` type I defined earlier
<img width="845" alt="screen shot 2019-01-14 at 4 30 03 pm" src="https://user-images.githubusercontent.com/14351638/51118771-d3501280-1819-11e9-9e12-d100032b0664.png">

But when I start an application, it crashes with an error
<img width="1242" alt="screen shot 2019-01-14 at 4 30 28 pm" src="https://user-images.githubusercontent.com/14351638/51118776-d519d600-1819-11e9-9000-19b8188e9b77.png">

Full error log is the following
```
(node:16478) UnhandledPromiseRejectionWarning: Error: 
      GraphQL-Modules Error: Schema is not valid!
      - #Module #149487813956593 doesn't have a valid schema!
      -- Cannot extend type "Query" because it does not exist in the existing schema.

      Possible solutions:
      - Check syntax errors in typeDefs
      - Make sure you import correct dependencies
    
    at GraphQLModule.buildSchemaAndInjector (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/node_modules/@graphql-modules/core/src/graphql-module.ts:483:17)
    at GraphQLModule.buildSchemaAndInjector (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/node_modules/@graphql-modules/core/src/graphql-module.ts:414:16)
    at GraphQLModule.get [as schema] (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/node_modules/@graphql-modules/core/src/graphql-module.ts:177:12)
    at Object.<anonymous> (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/src/server.ts:5:31)
    at Generator.next (<anonymous>)
    at /Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/src/server.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/src/server.ts:3:12)
    at Object.bootstrap (/Users/ifeature/Desktop/graphql-modules/examples/basic-with-dependency-injection/src/server.ts:13:12)
```

**Comment by ardatan** [comment]
Every single module has its own schema that is independent from each other. So before importing UserModule, the schema of UserModule is generated. Then the schema of UserModule is extended by AppModule’s. That’s why, the Query definition inside AppModule should be extension not UserModule’s. But, I recommend not to use extension nodes for root schema types; because every module may have its own query type definition.

**Comment by nakhodkiin** [comment]
Thank you for the explanation, it's much clearer now.
