### ISSUE TITLE
[Bug] Unable to use resolversComposition in app module

### ISSUE THREAD

**Issue by abhijeet1403** [Urigo/graphql-modules#356]
**Issue**: Using resolverComposition as a function on app module crashes the app
**Workaround**:
- Can use resolverComposition as function on every submodule with resolvers and typedefs
- Can use resolverComposition as a json object

**Desired Behaviour**:
Should be able to use resolverComposition as function on app module level

**Code**:
app.module.js
```
.
.
.
import { resolversComposition } from './auth/auth.composition';

export const AppModule = new GraphQLModule({
    name: 'App',
    imports: [
    .
    .
    .
    ],
    resolversComposition
});
```

auth.composition.js
```
export const resolversComposition = (args) => {
    console.log('resolversComposition');
    let result = {};
    const fieldsAndTypeToDirectivesMap = getFieldsWithDirectives(args.typeDefs);
    console.log(fieldsAndTypeToDirectivesMap);

    for (const fieldPath in fieldsAndTypeToDirectivesMap) {
        const directives = fieldsAndTypeToDirectivesMap[fieldPath];
        if (directives.length > 0) {
            result[fieldPath] = directives.map(directive => {
                if (DIRECTIVE_TO_GUARD[directive.name]) {
                    const mapperFn = DIRECTIVE_TO_GUARD[directive.name];
                    return mapperFn(directive.args);
                }

                return null;
            }).filter(a => a);
        }
    }
    return result;

}
```

Error
```
Error: 
      GraphQL-Modules Error: Schema is not valid!
      - #Module #App doesn't have a valid schema!
      -- Connection "default" was not found.

      Possible solutions:
      - Check syntax errors in typeDefs
      - Make sure you import correct dependencies
    
    at GraphQLModule.buildSchemaWithMakeExecutableSchema (/home/walkin/Walkin/walkin-server-monorepo/packages/walkin-platform/node_modules/@graphql-modules/core/src/graphql-module.ts:315:15)
    at GraphQLModule.get schema [as schema] (/home/walkin/Walkin/walkin-server-monorepo/packages/walkin-platform/node_modules/@graphql-modules/core/src/graphql-module.ts:331:12)
    at Object.<anonymous> (/home/walkin/Walkin/walkin-server-monorepo/packages/walkin-platform/src/index.js:16:29)
    at Module._compile (module.js:652:30)
    at babelWatchLoader (/home/walkin/Walkin/walkin-server-monorepo/packages/walkin-platform/node_modules/babel-watch/runner.js:51:13)
    at Object.require.extensions.(anonymous function) [as .js] (/home/walkin/Walkin/walkin-server-monorepo/packages/walkin-platform/node_modules/babel-watch/runner.js:62:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

I don't get the same error on using resolverComposition from examples like

```
import { GraphQLModule } from '@graphql-modules/core';

const MyModule = new GraphQLModule({
    /*...*/
    resolversComposition: {
        'Query.myQuery': [isAuthenticated(), hasRole('EDITOR')],
    },
});
```

**Comment by ardatan** [comment]
`Connection "default" was not found.` doesn't look related to GraphQL-Modules. I think you're using TypeORM, and trying to use it before calling `createConnection`.

**Comment by ardatan** [comment]
Closing this issue, feel free to open again if the problems persists
