### ISSUE TITLE
Import a Session provider in an application provider

### ISSUE THREAD

**Issue by deweve** [Urigo/graphql-modules#359]
I've tried to create a session provider to translate text, and I would like to use it with another application provider. This is the userProvider which use the translated provider which is a session provider

```typescript
import {Injectable, ProviderScope} from "@graphql-modules/core/dist/di";
import {ApolloError, UserInputError} from 'apollo-server-express';
import {TranslateProvider} from "../../common-module/Provider/translate.provider";

@Injectable({

})
export class UserProvider {
    constructor(private translateProvider: TranslateProvider) {

    }

   async editUser(user: string | User, args: any): Promise<User> {
            // ...
            if (user == null) {
                throw new ApolloError(this.translateProvider.translate('The user %s does not exist', user_id));
            }
           //...
    }
```
```typescript
export const UserModule = new GraphQLModule({
    typeDefs: loadSchemaFiles(__dirname + '/Schemas'),
    resolvers: loadResolversFiles(__dirname + '/Resolvers'),
    providers: [
        UserProvider,
    ],
    imports: [
        AuthModule,
        CommonModule
    ],
});
```
```typescript
export const CommonModule = new GraphQLModule({
    name: 'common',
    providers: [
        TranslateProvider
    ]
});
```

```typescript
@Injectable({
    scope: ProviderScope.Session
})
export class TranslateProvider {
    public translate: (phraseOrOptions: (string | i18n.TranslateOptions), ...replace: string[]) => string;

    constructor(private moduleSession: ModuleSessionInfo) {
        console.log('Translate Provider');
        this.translate = this.moduleSession.session.req.__;
    }

}
```
And when I call the function editUser for the first time, I think when user provider is   created there is the problem. This is the stacktrace : 

```     "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Context creation failed: ",
            "      GraphQL-Modules Error: Context couldn't be built!",
            "      - Module #index.ts_1687317041566921 couldn't build the context due to the following internal error!",
            "      -- ",
            "      GraphQL-Modules Error: Dependency Provider Not Found!",
            "      - Provider #ModuleSessionInfo couldn't be injected into Provider #TranslateProvider",
            "      -- Provider #ModuleSessionInfo is not provided in #Module common scope!",
            "",
            "      Possible solutions:",
            "      - Make sure you have imported the module of Provider #ModuleSessionInfo in the module of Provider #TranslateProvider",
            "  ",
            "      -- Error: ",
            "      GraphQL-Modules Error: Dependency Provider Not Found!",
            "      - Provider #ModuleSessionInfo couldn't be injected into Provider #TranslateProvider",
            "      -- Provider #ModuleSessionInfo is not provided in #Module common scope!",
            "",
            "      Possible solutions:",
            "      - Make sure you have imported the module of Provider #ModuleSessionInfo in the module of Provider #TranslateProvider",
            "  ",
            "    at Injector.get (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/di/src/injector.ts:130:19)",
            "    at Injector.get (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/di/src/injector.ts:145:26)",
            "    at dependencies.map.dependency (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/di/src/injector.ts:113:75)",
            "    at Array.map (<anonymous>)",
            "    at Injector.get (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/di/src/injector.ts:113:52)",
            "    at GraphQLModule.get injector [as injector] (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/core/src/graphql-module.ts:363:18)",
            "    at moduleNameContext$Map.set.Promise (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/core/src/graphql-module.ts:871:54)",
            "    at <anonymous>",
            "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
            "  ",
            "    at moduleNameContext$Map.set.Promise (/home/etienne/WebstormProjects/Vitrine-back/node_modules/@graphql-modules/core/src/graphql-module.ts:905:32)",
            "    at <anonymous>",
            "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
          ]
        }
```

**Comment by ardatan** [comment]
Session Scope Providers are created on each network request while Application Scope Providers are created once on server bootstrap. So, that's normal not to be able to access session scope providers from application scope ones. 
https://graphql-modules.com/docs/introduction/dependency-injection#session-scope

**Comment by deweve** [comment]
Ok, so if I want to create an auth session provider I will not be able to have it directly in my provider. Should I pass my session provider to the function which wants to use it?
```typescript
export default {
    Mutation {
         someMutation: (root, args, {injector}) => {
               const auhtProvider = injector.get(AuthProvider);
               injector.get(UserProvider).someFunction(args, authProvider);
        }
}
```

**Comment by ardatan** [comment]
It didn't look good to me. You can make `UserProvider` session-scoped as well, or inject your application scope provider into session scoped provider.

**Comment by deweve** [comment]
Okay, thanks for the advice, I will look for another implementation. My goal is to be able to have an error message in a different language.
