### ISSUE TITLE
Couldn't find type [schema] in any of the schemas.

### ISSUE THREAD

**Issue by Richard-Choooou** [Urigo/graphql-modules#426]
Hello, I have one module called "products"
```js
// index.ts

import { GraphQLModule } from '@graphql-modules/core'
import { Controller } from 'egg'
import 'graphql-import-node'
import classificationModule from '../classifications/index'
import { ProductsProvider } from './products.provider'
import resolvers from './resolvers'
import * as typeDefs from './schema.graphql'

export default new GraphQLModule({
    name: 'products',
    imports: [classificationModule],
    typeDefs,
    resolvers,
    providers: () => [ProductsProvider],
    extraSchemas: [classificationModule.schema],
    context(egg: Controller) {
        return {
            ...egg,
        }
    },
})

```

```
# schema
type Query {
    products(filters: ProductsFilter): [Product]!
    product(id: ID!):  Product
}

type Product {
    id: ID!
    name: String!
    class: Classification!  # <--- here
    # ...other fields
}

```

and another module called classifications

```js
// index.ts

import { GraphQLModule } from '@graphql-modules/core'
import { Controller } from 'egg'
import 'graphql-import-node'
import { classificationsProvider } from './classifications.provider'
import resolvers from './resolvers'
import * as typeDefs from './schema.graphql'

export default new GraphQLModule({
    name: 'classifications',
    typeDefs,
    resolvers,
    providers: () => [classificationsProvider],
    context(egg: Controller) {
        return {
            ...egg
        }
    }
})

```

```
type Classification {
    id: Int!
    name: String!
    products(filters: ProductsFilter): [Product]
}

input updateClassData {
    id: Int!
    name: String
}
```

Now, I try to use 'classification' schema in the products module, then got the error when I running
```
Error: [egg-core] load file: M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\app\controller\graphql2.ts, error: Field class: Couldn't find type Classification in any of the schemas.
    at collectNode (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import\src\definition.ts:154:15)
    at M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import\src\definition.ts:135:7
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import\src\definition.ts:134:26)
    at Object.completeDefinitionPool (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import\src\definition.ts:49:39)    at importSchema (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import\src\index.ts:127:18)
    at Object.graphQLRequire (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\graphql-import-node\index.js:5:30)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\app\new_graphql\products\index.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (M:\you-xiao-ke\you-xiao-ke-purchase-agent-server\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

How can I fix it? thanks.

**Comment by eiddie** [comment]
try `extend  type` to avoid [circular imports hell](https://medium.com/the-guild/manage-circular-imports-hell-with-graphql-modules-4b1611dee781)

**Comment by Richard-Choooou** [comment]
@eiddie  I think products and classifications merge to one schema will be a great solution. thanks a lot

**Comment by Richard-Choooou** [comment]
finally, I resolver the problem with this way

```js
// index.ts

import { GraphQLModule } from '@graphql-modules/core'
import 'graphql-import-node'
import * as productsTypeDefs from './products.graphql'
import { ProductsProvider } from './products.provider'
import productsResolvers from './products.resolvers'

export default new GraphQLModule({
    name: 'products',
    typeDefs: [productsTypeDefs],
    resolvers: [productsResolvers],
    providers: () => [ProductsProvider]
})

```

products.graphql
```
# import Classification from '../classifications/classifications.graphql'

type Product {
    id: ID!
    name: String!
    class: Classification!
}

```
classifications.graphql
```
# import Product from '../products/products.graphql'

type Classification {
    id: Int!
    name: String!
    products(filters: ProductsFilter): [Product]
}

```

look at the first line, there are import other schemas into the current schema.

more details see [https://github.com/prisma/graphql-import](https://github.com/prisma/graphql-import)

**Comment by dotansimha** [comment]
@Richard-Choooou If you are using GraphQL-Modules,  I'm not sure why you need to use `graphql-import`, only for the import syntax? 
Because graphql-modules already merges types it automatically, and the codegen can just read your entire schema with a glob expression (`src/**/*.graphql`) and merge it automatically.

**Comment by Richard-Choooou** [comment]
@dotansimha I try to use the 'extend type', but it's not useful. The official documentation doesn't tell me how to get a schema in another graphql files. And I must use 'graphql-import' to import a graphql file in typescript project, if not they will throw an error. Cause graphql files content aren't javascript code snippet. My English is not good, hope you understand these words.
