### ISSUE TITLE
how to use `extend` when I separate schema into pieces

### ISSUE THREAD

**Issue by dancon** [Urigo/graphql-modules#436]
The code like below:

`animal.graphql`

```
...
type Animal {
   type: String,
   name: String
}
```

`bird.graphql`

```
...
type Query {
  getBirds: [Animal]
}
// I extend Animal add `wing` filed
extend type Animal {
    wing: Int
}
```

`bird.module`

```
import BirdProvider from './bird.provider'
import * as typeDefs from './bird.graphql'
import resolvers from './bird.resolvers'
import animalModule from '../animalModule'

export default new GraphModule({
   typeDefs,
   resolvers,
   providers: [ BirdProvider ],
   imports: [ animalModule ]
})
```

when i run my server, I get error like below:

```
Error: Field getBirds: Couldn't find type Animal in any of the schemas.
    at collectNode (.../server/node_modules/graphql-import/src/definition.ts:154:15)
    at /Users/houquan/workspace/fe_dev/fe-panshi/server/node_modules/graphql-import/src/definition.ts:135:7
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (.../server/node_modules/graphql-import/src/definition.ts:134:26)
    at Object.completeDefinitionPool (.../server/node_modules/graphql-import/src/definition.ts:49:39)
    at importSchema (.../server/node_modules/graphql-import/src/index.ts:127:18)
    at Object.graphQLRequire (.../server/node_modules/graphql-import-node/index.js:5:30)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by ardatan** [comment]
Must be fixed in `graphql-import-node@0.0.3`
