### ISSUE TITLE
[Question] Contributing to website

### ISSUE THREAD

**Issue by wtrocki** [Urigo/graphql-modules#582]
Does website `npm run start` work for you?
Getting this error (most likely doing something wrong)

```
Error: Processing the following doc field in headerLinks within siteConfig.js: 'api/core/api-readme' It looks like there is no document with that id that exists in your docs directory. Please double check the spelling of your `doc` field and the `id` fields of your docs.
    at HeaderNav.makeLinks (/Users/wtrocki/Projects/sandbox/graphql-modules/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:191:15)
    at Array.map (<anonymous>)
    at HeaderNav.map [as renderResponsiveNav] (/Users/wtrocki/Projects/sandbox/graphql-modules/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:286:26)
    at HeaderNav.renderResponsiveNav [as render] (/Users/wtrocki/Projects/sandbox/graphql-modules/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:327:19)
    at processChild (/Users/wtrocki/Projects/sandbox/graphql-modules/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
    at resolve (/Users/wtrocki/Projects/sandbox/graphql-modules/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/wtrocki/Projects/sandbox/graphql-modul

```

**Comment by wtrocki** [comment]
Ok. `build:api-docs` needed to be triggered. Ignore this!
