### ISSUE TITLE
Use class metadata with provide using object

### ISSUE THREAD

**Issue by kesslerdev** [Urigo/graphql-modules#600]
the [injector.provide method](https://github.com/Urigo/graphql-modules/blob/master/packages/di/src/injector.ts#L74), dont use class metadata if argument is an object with `provide`, it should merge class metadata options in order to respect `@Injectable` provided options

example:
```js
// provider.js
class MyProvider{
}
module.exports = Injectable({ scope: ProviderScope.Session })(MyProvider)

```

```js
// module.js
module.exports = new GraphQLModule({
  providers: [
    {
      provide: 'myprovider',
      useClass: MyProvider,
    },
  ],
})
```

with this code the provider `myprovider` are in `ProviderScope.Application` not `ProviderScope.Session`

cf: https://github.com/Urigo/graphql-modules/pull/596

**Comment by ardatan** [comment]
You can use the following canary version;
```
0.7.10-alpha-ebb36c3.0+ebb36c3  
```

**Comment by laho** [comment]
Seems to me that this change breaks the dependency injection. When `provide: 'myprovider'` is a string and line 128 of the commit is calling getMetadata on that string, That results a TypeError.

Stack trace:
      at Object.getMetadata (node_modules/reflect-metadata/Reflect.js:354:23)
      at Injector.provide (node_modules/@graphql-modules/di/src/injector.ts:128:61)
      at new Injector (node_modules/@graphql-modules/di/src/injector.ts:47:14)
      at GraphQLModule.get injector [as injector] (node_modules/@graphql-modules/core/src/graphql-module.ts:472:48)
      at ModuleSessionInfo.get injector [as injector] (node_modules/@graphql-modules/core/src/module-session-info.ts:22:24)
      at new ModuleSessionInfo (node_modules/@graphql-modules/core/src/module-session-info.ts:6:10)
      at _sessionContext$Map.set.Promise (node_modules/@graphql-modules/core/src/graphql-module.ts:1287:43)
      at GraphQLModule._cache.contextBuilder (node_modules/@graphql-modules/core/src/graphql-module.ts:1276:13)
      at Promise.all.selfImports.map.module (node_modules/@graphql-modules/core/src/graphql-module.ts:1283:54)
          at Array.map (<anonymous>)
      at _sessionContext$Map.set.Promise (node_modules/@graphql-modules/core/src/graphql-module.ts:1283:33)
      at _cache.contextBuilder (node_modules/@graphql-modules/core/src/graphql-module.ts:1276:13)

Can you verify if this implementation works or have I misunderstood something?
