### ISSUE TITLE
Allowing non-graphql specific modules

### ISSUE THREAD

**Issue by fenos** [Urigo/graphql-modules#906]
Hello, 

Apparently **graphql-modules** will not allow importing modules that don't specify a schema definition. 

Let me give you an example:

```ts
// LoggerModule
class Logger {}
const LoggerModule = new GraphQLModule({
  name: "Logger",
  providers: [Logger]
});

// DatabaseModule
class DB {}
const DBModule = new GraphQLModule({
  name: "DB",
  imports: [LoggerModule],
  providers: [DB]
});


// App Module

const AppModule = new GraphQLModule({
  name: "App",
  imports: [
      DBModule,
      ...OtherGqlSpecificModules
  ],
});

await AppModule.schemaAsync
```

Since the **LoggerModule** didn't specify a gql schema, **graphql-modules** fails with the following error:

```
(node:69) UnhandledPromiseRejectionWarning: Error:
      GraphQL-Modules Error: Schema is not valid!
      - #Module #._6078098463828563 doesn't have a valid schema!
      -- Syntax Error: Unexpected <EOF>

      Possible solutions:
      - Check syntax errors in typeDefs
      - Make sure you import correct dependencies

    at _cacheAsync.schemaAsync.Promise (/sandbox/node_modules/@graphql-modules/core/src/graphql-module.ts:440:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at Object.<anonymous> (/sandbox/node_modules/ts-node/src/bin.ts:151:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:69) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:69) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are nothandled will terminate the Node.js process with a non-zero exit code.
```

Being able to create non-graphql specific modules will definitely help to maintain the module structure and create re-usable modules, still benefitting of the module DI.

This could be a bug because I remember in the past it used to work.

[Demo reproduction](https://codesandbox.io/s/typescript-node-dwq7e?fontsize=14&hidenavigation=1&theme=dark)

**Comment by fenos** [comment]
Ok, this is definitely a regression and a bug. I've raised the PR above which fixes it
